# This example creates two orgVdcNetworks - one natRouted, the other isolated
#
# dns settings and ip_ranges are optional
#
# example-net-isolated-shared has is_shared set, which means that it will be
# available across all vDCs in the org (though is 'owned' by 'Our vDC').
#
---
org_vdc_networks:

- name: example-net-routed-1
  description: "Frontend example network" 
  vdc_name: 'Our vDC'
  fence_mode: natRouted
  edge_gateway: Gateway-FRONTEND
  netmask: 255.255.255.0
  gateway: 192.0.2.1
  dns1: 8.8.8.8
  dns2: 8.8.4.4
  dns_suffix: testing.example.com
  ip_ranges:
    - start_address: 192.0.2.11
      end_address: 192.0.2.40
    - start_address: 192.0.2.101
      end_address: 192.0.2.140

- name: example-net-isolated-shared
  vdc_name: 'Our vDC'
  fence_mode: isolated
  is_shared: true
  netmask: 255.255.255.0
  gateway: 198.51.100.1
  dns1: 8.8.8.8
  dns2: 8.8.4.4
  dns_suffix: testing.example.com
  ip_ranges:
    - start_address: 198.51.100.11
      end_address: 198.51.100.40
    - start_address: 198.51.100.101
      end_address: 198.51.100.140

